import Footer from "@/components/Footer"
import Header from "@/components/Header"
import Head from "next/head"
import './globals.css'
import './Home.module.css'
import React from 'react'
import { Metadata } from "next"

export const metadata : Metadata = {
    title: 'Weka movies',
    description: 'Welcome to Weka movies',
    icons:'/static/large-WOMJa9L29-transformed.png'

  }


export default function RootLayout({
    // Layouts must accept a children prop.
    // This will be populated with nested layouts or pages
    children,
  } : {children : React.ReactNode }) {
    return (
      <html lang="en">
        <Head>
            <title>Weka Movies</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests"/>
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <body>
             <Header/>
            {children}
            <Footer/>
        </body>
      </html>
    )
  }