import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import ToggleButton from '@mui/material/ToggleButton';
import ToggleButtonGroup from '@mui/material/ToggleButtonGroup';
import { useRef, useState } from 'react';
import MoviesList from '@/components/movies';
import { useRouter } from 'next/router';
import Video from '@/components/Video';


export default function Home({data}) {
  const [enabled, setEnabled] = useState(false);
  const [search , setSearch] = useState('');
  const router = useRouter()
 
  const handleSubmit = (e) =>{
    e.preventDefault()
    router.push(`/Search/${search}`)
  }
  return (
    <>
      <Head>
        <title>Weka Movies</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=' lg:px-40 flex flex-col gap-9'> 
        <div className='relative'>
           <Image width={100000} height={1000000}  className='object-cover w-full h-[600px] brightness-50 relative' src={`https://www.themoviedb.org/t/p/w1280${data}`} alt="main" />
            <div className='absolute z-10  text-slate-100 -top-0 ml-3 lg:m-24 mt-60 lg:mt-72 w-9/12  h-36 gap-3 flex flex-col'>
              <div>
                <h1 className='text-5xl '>Welcome ,</h1>
                <p className='text-2xl'><span className='text-[#F4181C]'>Ali ashraf</span>  to my frist big website</p>
              </div>
              <form className='bg-white rounded-full w-full h-1/3   ' onSubmit={handleSubmit}>
                <input type="text " value={search} onChange={(e) => setSearch(e.target.value) } className='rounded-full w-[80%] lg:w-[90%]  px-3 focus-within:outline-none text-gray-700' placeholder='Search for Movies and Tv show '/>
                <button type="submit" className='bg-[#F4181C] rounded-full w-[20%] lg:w-[10%] h-[48px] '>Search</button>
              </form>
            </div>
        </div>
        <div className='text-white  flex flex-col  gap-6'>
          <div className='flex flex-row gap-6 '>
            <h1 className='text-header'>Treading</h1>
             <div className='flex gap-10 border-2 border-[#F4181C] px-2  rounded-full w-44 h-8 relative mt-1'>
                <button onClick={() => setEnabled(false)} className={`z-20 ${!enabled && 'text-black'}`}>
                    Today 
                </button>
                <div className={`absolute  bg-[#F4181C]  w-16 h-8  -left-1 -top-[2px] rounded-full  ${ enabled ? 'w-[6.3rem] translate-x-[80%]  duration-150 ' : 'duration-150' }`}>
                  {' '}
                </div>
                <button onClick={() => setEnabled(true)} className={`z-20    ${enabled && 'text-black'}  `}>
                  This Week
                </button>
             </div>
          </div>
          <MoviesList url={`https://api.themoviedb.org/3/trending/all/${enabled ? 'week' : 'day'}?`}/>
          <Video/>
        </div>

      </main>
    </>
  )
}

export const getServerSideProps = async (ctx) => {
  const response  = await fetch(`https://api.themoviedb.org/3/trending/all/week?api_key=${process.env.NEXT_PUBLIC_DB_key}`); 
  const data = await response.json();
  const image = data.results[Math.floor(Math.random() * (19 - 0 + 1)) + 0].backdrop_path ; 
  return {
    props: {
      data : image , 
    } 
  }
} 